var verbs = [
	{letter: "A", first_form: "awake", second_form: "awoke", third_form: "awaken", translate: "a trezi"},
	{letter: "B", first_form: "be", second_form: "was/were", third_form: "been", translate: "a fi"},
	{letter: "B", first_form: "become", second_form: "became", third_form: "become", translate: "a deveni"},
	{letter: "B", first_form: "burn", second_form: "burn", third_form: "burn", translate: "a arde"},
	{letter: "B", first_form: "build", second_form: "built", third_form: "built", translate: "a construi"},
	{letter: "B", first_form: "bet", second_form: "bet", third_form: "bet", translate: "a paria"},
	{letter: "B", first_form: "buy", second_form: "bought", third_form: "bought", translate: "a cumpara"},
	{letter: "B", first_form: "bring", second_form: "brought", third_form: "brought", translate: "a aduce"},
	{letter: "B", first_form: "break", second_form: "broke", third_form: "broken", translate: "a rupe, a sparge"},
	{letter: "B", first_form: "begin", second_form: "began", third_form: "begun", translate: "a incepe"},
	{letter: "B", first_form: "blow", second_form: "blew", third_form: "blown", translate: "a sufla"},
	{letter: "B", first_form: "bleed", second_form: "bled", third_form: "bled", translate: "a sangera"},
	
	{letter: "C", first_form: "cut", second_form: "cut", third_form: "cut", translate: "a taia"},
	{letter: "C", first_form: "cost", second_form: "cost", third_form: "cost", translate: "a costa"},
	{letter: "C", first_form: "choose", second_form: "chose", third_form: "chosen", translate: "a alege"},
	{letter: "C", first_form: "catch", second_form: "caught", third_form: "caught", translate: "a prinde"},
	{letter: "C", first_form: "come", second_form: "came", third_form: "come", translate: "a veni"},
	
	{letter: "D", first_form: "do", second_form: "did", third_form: "done", translate: "a face"},
	{letter: "D", first_form: "dig", second_form: "dug", third_form: "dug", translate: "a sapa"},
	{letter: "D", first_form: "dream", second_form: "dreamt", third_form: "dreamt", translate: "a visa"},
	{letter: "D", first_form: "drink", second_form: "drank", third_form: "drunk", translate: "a bea"},
	{letter: "D", first_form: "draw", second_form: "drew", third_form: "drawn", translate: "a visa"},
	{letter: "D", first_form: "drive", second_form: "drove", third_form: "driven", translate: "a conduce"},
	
	{letter: "E", first_form: "eat", second_form: "ate", third_form: "eaten", translate: "a manca"},
	
	{letter: "F", first_form: "fall", second_form: "fell", third_form: "fallen", translate: "a cadea"},
	{letter: "F", first_form: "feel", second_form: "felt", third_form: "felt", translate: "a simti"},
	{letter: "F", first_form: "feed", second_form: "fed", third_form: "fed", translate: "a hrani"},	
	{letter: "F", first_form: "fight", second_form: "fought", third_form: "fought", translate: "a lupta"},
	{letter: "F", first_form: "find", second_form: "found", third_form: "found", translate: "a gasi"},
	{letter: "F", first_form: "fly", second_form: "flew", third_form: "flown", translate: "a zbura"},
	{letter: "F", first_form: "forget", second_form: "forgot", third_form: "forgotten", translate: "a uita"},
	{letter: "F", first_form: "forgive", second_form: "forgave", third_form: "forgiven", translate: "a ierta"},
	{letter: "F", first_form: "freeze", second_form: "froze", third_form: "frozen", translate: "a ingheta"},
	
	{letter: "G", first_form: "get", second_form: "got", third_form: "got", translate: "a primi"},
	{letter: "G", first_form: "give", second_form: "gave", third_form: "given", translate: "a da"},
	{letter: "G", first_form: "go", second_form: "went", third_form: "gone", translate: "a merge"},
	{letter: "G", first_form: "grow", second_form: "grew", third_form: "grown", translate: "a creste"},

	{letter: "H", first_form: "have", second_form: "had", third_form: "had", translate: "a avea"},
	{letter: "H", first_form: "hear", second_form: "heard", third_form: "heard", translate: "a auzi"},
	{letter: "H", first_form: "hide", second_form: "hid", third_form: "hidden", translate: "a ascunde"},
	{letter: "H", first_form: "hit", second_form: "hit", third_form: "hit", translate: "a lovi"},
	{letter: "H", first_form: "hold", second_form: "held", third_form: "held", translate: "a tine"},
	{letter: "H", first_form: "hurt", second_form: "hurt", third_form: "hurt", translate: "a rani"},
	
	{letter: "K", first_form: "keep", second_form: "kept", third_form: "kept", translate: "a pastra"},
	{letter: "K", first_form: "know", second_form: "knew", third_form: "known", translate: "a sti"},
	
	{letter: "L", first_form: "learn", second_form: "learnt", third_form: "learnt", translate: "a invata"},
	{letter: "L", first_form: "leave", second_form: "left", third_form: "left", translate: "a parasi, a pleca"},
	{letter: "L", first_form: "lend", second_form: "lent", third_form: "lent", translate: "a imprumuta"},
	{letter: "L", first_form: "let", second_form: "let", third_form: "let", translate: "a lasa"},
	{letter: "L", first_form: "light", second_form: "lit", third_form: "lit", translate: "a aprinde"},
	{letter: "L", first_form: "lose", second_form: "lost", third_form: "lost", translate: "a pierde"},

	{letter: "M", first_form: "make", second_form: "made", third_form: "made", translate: "a face"},
	{letter: "M", first_form: "mean", second_form: "meant", third_form: "meant", translate: "a insemna"},
	{letter: "M", first_form: "meet", second_form: "met", third_form: "met", translate: "a intalni"},

	{letter: "P", first_form: "pay", second_form: "paid", third_form: "paid", translate: "a plati"},
	{letter: "P", first_form: "put", second_form: "put", third_form: "put", translate: "a pune"},

	{letter: "Q", first_form: "quit", second_form: "quit", third_form: "quit", translate: "a renunta"},

	{letter: "R", first_form: "read", second_form: "read", third_form: "read", translate: "a citi"},
	{letter: "R", first_form: "ride", second_form: "rode", third_form: "ridden", translate: "a calari"},
	{letter: "R", first_form: "ring", second_form: "rang", third_form: "rung", translate: "a suna"},
	{letter: "R", first_form: "rise", second_form: "rose", third_form: "risen", translate: "a rasari"},
	{letter: "R", first_form: "run", second_form: "ran", third_form: "run", translate: "a alerga"},
	
	{letter: "S", first_form: "say", second_form: "said", third_form: "said", translate: "a spune"},
	{letter: "S", first_form: "see", second_form: "saw", third_form: "seen", translate: "a vedea"},
	{letter: "S", first_form: "sell", second_form: "sold", third_form: "sold", translate: "a vinde"},
	{letter: "S", first_form: "send", second_form: "sent", third_form: "sent", translate: "a trimite"},
	{letter: "S", first_form: "set", second_form: "set", third_form: "set", translate: "a regla, a seta"},
	{letter: "S", first_form: "shake", second_form: "shook", third_form: "shaken", translate: "a scutura"},
	{letter: "S", first_form: "shoot", second_form: "shot", third_form: "shot", translate: "a trage (cu arma)"},
	{letter: "S", first_form: "shut", second_form: "shut", third_form: "shut", translate: "a inchide"},
	{letter: "S", first_form: "sing", second_form: "sang", third_form: "sung", translate: "a canta"},
	{letter: "S", first_form: "sink", second_form: "sank", third_form: "sunk", translate: "(a se) scufunda"},
	{letter: "S", first_form: "sit", second_form: "sat", third_form: "sat", translate: "a aseza, a se aseza"},
	{letter: "S", first_form: "sleep", second_form: "slept", third_form: "slept", translate: "a adormi"},
	{letter: "S", first_form: "smell", second_form: "smelt", third_form: "smelt", translate: "a mirosi"},
	{letter: "S", first_form: "speak", second_form: "spoke", third_form: "spoken", translate: "a vorbi"},
	{letter: "S", first_form: "spend", second_form: "spent", third_form: "spent", translate: "a cheltui, a petrece timp"},
	{letter: "S", first_form: "stand", second_form: "stood", third_form: "stood", translate: "a sta in picioare"},
	{letter: "S", first_form: "steal", second_form: "stole", third_form: "stolen", translate: "a fura"},
	{letter: "S", first_form: "sting", second_form: "stung", third_form: "stung", translate: "a impunge"},
	{letter: "S", first_form: "stink", second_form: "stank", third_form: "stunk", translate: "a pute, a mirosi urat"},
	{letter: "S", first_form: "swim", second_form: "swam", third_form: "swum", translate: "a inota"},
	
	{letter: "T", first_form: "take", second_form: "took", third_form: "taken", translate: "a duce, a prinde"},
	{letter: "T", first_form: "teach", second_form: "taught", third_form: "taught", translate: "a invsta"},
	{letter: "T", first_form: "tell", second_form: "told", third_form: "told", translate: "a spune, a povesti"},
	{letter: "T", first_form: "think", second_form: "thought", third_form: "thought", translate: "a se gandi"},
	{letter: "T", first_form: "throw", second_form: "threw", third_form: "thrown", translate: "a arunca"},

	{letter: "U", first_form: "understand", second_form: "understood", third_form: "understood", translate: "a intelege"},

	{letter: "W", first_form: "wake", second_form: "woke", third_form: "woken", translate: "a trezi"},
	{letter: "W", first_form: "wear", second_form: "wore", third_form: "worn", translate: "a purta"},
	{letter: "W", first_form: "weep", second_form: "wept", third_form: "wept", translate: "a plange"},
	{letter: "W", first_form: "wet", second_form: "wet", third_form: "wet", translate: "a uda"},
	{letter: "W", first_form: "win", second_form: "won", third_form: "won", translate: "a castiga"},
	{letter: "W", first_form: "write", second_form: "wrote", third_form: "written", translate: "a scrie"},
];