module.exports = Object.freeze({
    CONTACT: {
        DE: {
            country: "Rumänien", 
            city: "Bukarest", 
            map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306], 
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148",
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",            
        },
        ENG: {
            country: "Romania", 
            city: "Bucharest", 
            map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306], 
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148",
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",
        },
        ES: {
            country: "Rumanía", 
            city: "Bucarest", 
            map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306],
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148",
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",            
        },
        FR: {
            country: "Roumanie", 
            city: "Bucarest", 
            map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306], 
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148",
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",
        },
        IT: {
            country: "Romania", 
            city: "Bucarest", 
            map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306], 
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148"},
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",
        PT: {
            country: "Romênia", 
            city: "Bucareste", 
            map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306], 
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148",
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",
        },
        RO: {
            country: "România", 
            city: "București", 
            map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306], 
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148"},
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",
        RU: {
            country: "Румыния", 
            city: "Бухарест", map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306], 
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148",
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",
        },
        ZH: {
            country: "罗马尼亚", 
            city: "布加勒斯特", 
            map: {lat: 44.469663, lng: 26.096306}, 
            marker: [44.439663, 26.096306], 
            email: "oanapopescu93@gmail.com", 
            phone: "+40729699148", 
            phone_text: "(+40) 729.699.148",
            linkedin: "https://www.linkedin.com/in/oanapopescu93",
            github: "https://github.com/oanapopescu93",
        },
    },
    SKILLS_TITLE: ['frontend', 'backend', 'other'],
    SKILLS: [
        {name: "HTML, CSS, Bootstrap", value: 100, type: "frontend"},
        {name: "JavaScript, Jquery", value: 100, type: "frontend"},
        {name: "React, Redux", value: 90, type: "frontend"},
        {name: "NodeJs, Express", value: 75, type: "backend"},
        {name: "Websockets", value: 75, type: "backend"},
        {name: "MySQL", value: 50, type: "backend"},
        {name: "Version control GIT", value: 50, type: "other"},
        {name: "HTML Canvas", value: 90, type: "frontend"},
        {name: "Photoshop", value: 30, type: "other"},
    ],
    LANGUAGES: [
        {name: "English", name: "english", level: "B2", perc: 80},
        {name: "German", name: "german", level: "A2", perc: 20},
        {name: "Romania", name: "romanian", level: "native", perc: 100},
    ],
    EDUCATION: [
        {
            school_name: "school_name01", 
            period: "school_period01",
            description: "school_description01"
        },
        {
            school_name: "school_name02", 
            title: "school_title02",
            period: "school_period02", 
            location: "school_location", 
            description: "school_description02"
        },
        {
            school_name: "school_name03", 
            period: "school_period03", 
            location: "school_location", 
            description: "school_description03"
        },
    ],
    EXPERIENCE: [
        {
            job_title: "job_title01", 
            period: "period01", 
            company_name: "company_name01", 
            company_description: "company_description01", 
            job_location: "job_location", 
            job_description: "HTML, CSS, Bootstrap, Javascript, Jquery, React/Redux, NodeJs, HTML canvas", 
            job_description_list: [
                "job_description_list011",
                "job_description_list012",
                "job_description_list013",
                "job_description_list014",
                "job_description_list015",
                "job_description_list016",
                "job_description_list017",
            ],
            link_company: "https://idriveglobal.com",
            projects: [
                {project_name: "Nexus", project_link: "https://idriveglobal.com/fleet-management-platform/"},
                {project_name: "Iris", project_link: "https://idriveglobal.com/fleet-management-platform/"},
            ],
        },
        {
            job_title: "job_title02", 
            period: "period02", 
            company_name: "company_name02", 
            job_location: "job_location", 
            job_description: "HTML, CSS, Bootstrap, Javascript, Jquery, Photoshop, React/Redux, NodeJs", 
            platform_used: "Wordpress, Magento",
            projects: [
                {project_name: "Clubul sportiv RealGym", project_link: "portofolio"},
                {project_name: "Noblisime", project_link: "portofolio"},
                {project_name: "Exclusive doors", project_link: "portofolio"},
                {project_name: "Credimag", project_link: "portofolio"},
                {project_name: "Konart", project_link: "portofolio"},
            ],
            personal_projects: [
                {project_name: "Casino", project_link: "portofolio"},
                {project_name: "E-commerce Shop", project_link: "portofolio"},
            ]
        },
        {
            job_title: "job_title03", 
            period: "period03", 
            company_name: "company_name03", 
            company_description: "company_description03", 
            job_location: "job_location", 
            job_description: "HTML, CSS, Bootstrap, Javascript, Jquery, Photoshop", 
            job_description_list: [
                "job_description_list031",
                "job_description_list032",
                "job_description_list033",
                "job_description_list034",
            ],
            platform_used: "Magento",
            accomplishments: "Learnt Magento",
            link_company: "https://www.salomon.ro/",
            projects: [
                {project_name: "Salomon site", project_link: "https://www.salomon.ro/"},
            ],
        },
        {
            job_title: "job_title04", 
            period: "period04", 
            company_name: "company_name04", 
            company_description: "company_description04", 
            job_location: "job_location", 
            job_description: "HTML, CSS, Bootstrap, Javascript, Jquery, Photoshop",
            job_description_list: [
                "job_description_list041",
                "job_description_list042",
                "job_description_list043",
                "job_description_list044",
            ],
            link_company: "https://www.expremio.com/",
            projects: [
                {project_name: "Pizza Hut Delivery", project_link: "portofolio"},
                {project_name: "City Grill", project_link: "portofolio"},
            ],
        },  
    ],
    PORTOFOLIO_LIST: ["webapps", "websites", "games"],
    PORTOFOLIO_ITEMS: {
        webapps: [
            {
                title: "portofolio_title01",
                link: "https://idriveglobal.com/fleet-management-platform/",
                src: "/img/pics/nexus.png",
                used: ["HTML", "CSS", "Javascript", "React", "Redux", "DevExtreme", "Leaflet", "NodeJS"],
                img_alt: "nexus",
                img_title: "nexus",
                description: "portofolio_description01"
            },
            {
                title: "portofolio_title02",
                link: "https://bunny-bet-casino.onrender.com/",
                src: "/img/pics/bunnybet.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "React", "Redux", "NodeJS", "Express", "Socket.IO", "HTML Canvas", "MySQL"],
                git: "https://github.com/oanapopescu93/casino",
                img_alt: "nodejs react casino",
                img_title: "nodejs react casino",
                description: "portofolio_description02"
            },
            {
                title: "portofolio_title03",
                link: "https://the-book-mouse.onrender.com",
                src: "/img/pics/the_book_mouse.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "React", "Redux", "NodeJS", "Express", "Socket.IO", "HTML Canvas", "MySQL"],
                git: "https://github.com/oanapopescu93/bookstore",
                img_alt: "nodejs react casino",
                img_title: "nodejs react casino",
                description: "portofolio_description03"
            },
            {
                title: "portofolio_title22",
                src: "/img/pics/blockchain.png",
                used: ["NodeJS", "Express", "Websockets", "Blockchain", "React", "Javascript", "CSS"],
                git: "https://github.com/oanapopescu93/blockchain",
                img_alt: "blockchain app",
                img_title: "blockchain app",
                description: "portofolio_description22"
            },
        ],
        websites: [
            {
                title: "portofolio_title06",
                link: "https://idriveglobal.com/fleet-management-platform/",
                src: "/img/pics/globalcenter.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "React", "Redux", "HTML Canvas", "DevExtreme", "Leaflet"],
                img_alt: "idrive global",
                img_title: "idrive global",
                description: "portofolio_description06"
            },          
            {
                title: "portofolio_title05",
                link: "https://www.salomon.ro",
                src: "/img/pics/salomon.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Photoshop"],
                platform: "Magento",
                img_alt: "salomon",
                img_title: "salomon",
                description: "portofolio_description05"
            },            
            {
                title: "portofolio_title07",
                link: "http://clubulsportivrealgym.ro",
                src: "/img/pics/realgym.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Photoshop", "PHP"],
                platform: "Wordpress",
                img_alt: "clubul sportiv realgym karate kickbox",
                img_title: "clubul sportiv realgym karate kickbox",
                description: "portofolio_description07"
            },
            {
                title: "portofolio_title08",
                link: "https://noblisime.ro",
                src: "/img/pics/noblisime.jpg",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Photoshop"],
                platform: "Magento",
                img_alt: "noblisime",
                img_title: "noblisime",
                description: "portofolio_description08"
            },
            {
                title: "portofolio_title09",
                link: "http://www.kon-art.ro",
                src: "/img/pics/konart.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Photoshop"],
                platform: "Magento",
                img_alt: "konart",
                img_title: "konart",
                description: "portofolio_description09"
            },
            {
                title: "portofolio_title10",
                link: "https://exclusivedoors.ro",
                src: "/img/pics/exclusivedoor.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Photoshop"],
                platform: "Magento",
                img_alt: "exclusive doors",
                img_title: "exclusive doors",
                status: "still in localhost",
                description: "portofolio_description10"
            },
            {
                title: "portofolio_title11",
                link: "https://www.pizzahutdelivery.ro/ro",
                src: "/img/pics/PHD01.jpg",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Photoshop"],
                img_alt: "pizza hut delivery",
                img_title: "pizza hut delivery",
                description: "portofolio_description11"
            },
            {
                title: "portofolio_title12",
                link: "https://citygrill.ro/ro",
                src: "/img/pics/citygrill.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Photoshop"],
                platform: "October CMS",
                img_alt: "city grill",
                img_title: "city grill",
                description: "portofolio_description12"
            }, 
            {
                title: "portofolio_title13",
                link: "http://aperider.com/",
                src: "/img/pics/aperider.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Photoshop"],
                img_alt: "ape rider biciclete",
                img_title: "ape rider biciclete",
                description: "portofolio_description13"
            },
        ],        
        games: [
            {
                title: "portofolio_title20",
                link: "/portofolio/connect4/index.html",
                src: "/img/pics/connect4.jpg",
                used: ["HTML", "CSS", "Javascript"],
                git: "https://github.com/oanapopescu93/connect4",
                img_alt: "connect 4 game",
                img_title: "connect 4 game",
            },
            {
                title: "portofolio_title14",
                link: "/portofolio/flip_cards/game-flip-card.html",
                src: "/img/pics/game-flip-card.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery"],
                git: "https://github.com/oanapopescu93/flip_cards",
                img_alt: "halloween flip card game",
                img_title: "halloween flip card game",
            },
            {
                title: "portofolio_title21",
                link: "/portofolio/battleship/index.html",
                src: "/img/pics/battleship.jpg",
                used: ["HTML", "CSS", "Javascript"],
                git: "https://github.com/oanapopescu93/battleship",
                img_alt: "battleship game",
                img_title: "battleship card game",
            },
            {
                title: "portofolio_title16",
                link: "/portofolio/maze/index.html",
                src: "/img/pics/maze.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "HTML Canvas"],
                git: "https://github.com/oanapopescu93/backtrack_mouse_maze",
                img_alt: "backtracking maze game",
                img_title: "backtracking maze game",
            },
            {
                title: "portofolio_title15",
                link: "/portofolio/chatbot/index.html",
                src: "/img/pics/chatbot.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "Machine Learning"],
                git: "https://github.com/oanapopescu93/chatbot",
                img_alt: "chatbot",
                img_title: "speak with oana chatbot",
            },            
            {
                title: "portofolio_title17",
                link: "/portofolio/snake/index.html",
                src: "/img/pics/snake.jpg",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "HTML Canvas"],
                git: "https://github.com/oanapopescu93/snake_game",
                img_alt: "snake game",
                img_title: "snake game",
            },
            {
                title: "portofolio_title18",
                link: "/portofolio/space_invader/index.html",
                src: "/img/pics/game_icon.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery", "HTML Canvas"],
                git: "https://github.com/oanapopescu93/space_invader",
                img_alt: "space invaders",
                img_title: "space invaders - game to cure office boredom",
                description: "portofolio_description18"
            },
            {
                title: "portofolio_title19",
                link: "/portofolio/irregular_verbs/index.html",
                src: "/img/pics/game-quiz.png",
                used: ["HTML", "CSS", "Bootstrap", "Javascript", "Jquery"],
                git: "https://github.com/oanapopescu93/irregular_verbs",
                img_alt: "irregular verbs quiz game",
                img_title: "irregular verbs quiz game",
            },
        ],
    },    
    TUTORIALS: [
        {
            name: "Javascript promises",
            description: "Understand and use promises in javascript",
            used: ["javascript", "jquery"],
            link: "https://github.com/oanapopescu93/tutorial_javascript_promises",
            type: "javascript",
        },
        {
            name: "React crud",
            description: "react app for managing books",
            used: ["javascript", "jquery", "react", "redux"],
            link: "https://github.com/oanapopescu93/tutorial_react_crud",
            type: "react",
        },
        {
            name: "React print pdf",
            description: "React app to print a pdf",
            used: ["javascript", "react", "jquery"],
            link: "https://github.com/oanapopescu93/tutorial_react_print_pdf",
            type: "react",
        },
        {
            name: "React export pdf",
            description: "React app that exports text, images and svg",
            used: ["javascript", "react", "jquery"],
            link: "https://github.com/oanapopescu93/react_export_pdf",
            type: "react",
        },
        {
            name: "React module",
            description: "Tutorial react module",
            used: ["javascript", "react", "jquery"],
            link: "https://github.com/oanapopescu93/tutorial_react_module",
            type: "react",
        },
        {
            name: "NodeJs App",
            description: "chat with socket.io, weather app, and tic-toc game",
            used: ["javascript", "jquery", "nodejs", "socket.io", "express"],
            link: "https://github.com/oanapopescu93/nodeapp",
            type: "nodejs",
        },
        {
            name: "HTML Canvas graphics",
            description: "Pie and doughnuts chart tutorial",
            used: ["javascript", "jquery", "HTML Canvas"],
            link: "https://github.com/oanapopescu93/pie_doughnut_chart",
            type: "javascript",
        },
        {
            name: "Game of life",
            description: "A tutorial on how to generate lanscape",
            used: ["javascript", "jquery", "HTML Canvas"],
            link: "https://github.com/oanapopescu93/game_of_live_rpg",
            type: "javascript",
        },        
        {
            name: "weather_arduino",
            description: "weather app made with arduino and embeded C",
            used: ["arduino", "embeded C", "LoRa microcontroller"],
            link: "https://github.com/oanapopescu93/weather_arduino",
            type: "embedded c",
        },
        {
            name: "weather_api_arduino",
            description: "weather app made with arduino and embeded C",
            used: ["arduino", "embeded C", "LoRa microcontroller"],
            link: "https://github.com/oanapopescu93/weather_api_arduino",
            type: "embedded c",
        },
        {
            name: "arduino_date_time",
            description: "embeded C fundamentals and idiot proofing an app",
            used: ["arduino", "embeded C", "LoRa microcontroller"],
            link: "https://github.com/oanapopescu93/arduino_date_time",
            type: "embedded c",
        },
        {
            name: "Python basics",
            description: "python fundamentals and idiot proofing an app",
            used: ["python"],
            link: "https://github.com/oanapopescu93/tutorial_python_basics",
            type: "python",
        },
        {
            name: "Tic Tac Toe",
            description: "A Tic Tac Toe game in C++",
            used: ["C++"],
            link: "https://github.com/oanapopescu93/tic_tac_toe_cpp",
            type: "c++",
        },
    ],
})